# Only the internal scan job definition
jobs:
  - name: scan-internal
    public: true
    plan:
      - get: contexts # your CI repo’s contexts folder
      - get: runner-image # built by common-pipelines
      - task: zap-scan
        file: repo/ci/tasks/zap-scan.yml
        input_mapping:
          contexts: contexts
        params:
          SCAN_MODE: internal
          TARGET_URL: ((internal-target-url))
          CREDHB_CRED: ((credentials.internal))
      - put: zap-report-archive
        params:
          file: zap-report/report.json
