# job that sets all the rest
jobs:
  - name: set-self
    plan:
      - in_parallel:
          - get: src
            trigger: true
      - set_pipeline: self
        file: src/ci/container/pipeline.yml

  - name: set-base-pipelines
    plan:
      - get: src
        trigger: true
        passed: [set-self]
      - across:
          - var: name # repo, pipeline, and image name; all the same.
            values:
              - ubuntu-hardened
              - ubuntu-hardened-stig

        do:
          - set_pipeline: ((.:name))
            file: src/container/pipeline-base.yml
            var_files:
              # Contrary to Concourse docs, earlier values override later ones.
              # See https://github.com/concourse/concourse/issues/5455
              - src/ci/container/base/((.:name))/vars.yml
              - src/ci/container/base/base_vars.yml

  - name: set-internal-pipelines
    plan:
      - get: src
        trigger: true
        passed: [set-self]
      - across:
          - var: name # repo, pipeline, and image name; all the same.
            values:
              - bosh-deployment-resource
              - cf-resource
              - cflinuxfs4-hardened-candidate
              - cg-csb
              - concourse-http-jq-resource
              - cron-resource
              - csb-helper
              - external-domain-broker-migrator-testing
              - external-domain-broker-testing
              - general-task
              - github-pr-resource
              - github-release-resource
              - legacy-domain-certificate-renewer-testing
              - oci-build-task
              - opensearch-dashboards-testing
              - opensearch-testing
              - paketo-jammy-full-hardened-candidate
              - playwright-python
              - pulledpork
              - s3-resource
              - s3-simple-resource
              - slack-notification-resource
              - zap-runner

        do:
          - set_pipeline: ((.:name))
            file: src/container/pipeline-internal.yml
            var_files:
              # Contrary to Concourse docs, earlier values override later ones.
              # See https://github.com/concourse/concourse/issues/5455
              - src/ci/container/internal/((.:name))/vars.yml
              - src/ci/container/internal/base_vars.yml

  - name: set-external-pipelines
    plan:
      - get: src
        trigger: true
        passed: [set-self]
      - across:
          - var: name # repo, pipeline, and image name; all the same.
            values:
              - bosh-io-release-resource
              - bosh-io-stemcell-resource
              - cf-cli-resource
              - cloud-service-broker
              - email-resource
              - git-resource
              - openresty
              - pool-resource
              - registry-image-resource
              - semver-resource
              - time-resource
        do:
          - set_pipeline: ((.:name))
            file: src/container/pipeline-external.yml
            var_files:
              # Contrary to Concourse docs, earlier values override later ones.
              # See https://github.com/concourse/concourse/issues/5455
              - src/ci/container/external/((.:name))/vars.yml
              - src/ci/container/external/base_vars.yml

  - name: set-pages-pipelines
    plan:
      - get: src
        trigger: true
        passed: [set-self]
      - across:
          - var: name # repo, pipeline, and image name; all the same.
            values:
              - dind
              - node-v20
              - python-v3.11
              - redis-v7.2
              - nginx-v1
              - postgres-v15
              - zap
        do:
          - set_pipeline: image-((.:name))
            file: src/container/pipeline-pages.yml
            team: pages
            var_files:
              - src/ci/container/pages/((.:name))/vars.yml
              - src/ci/container/pages/base_vars.yml

  - name: container-instance-tracking
    plan:
      - get: src
      - get: cg-scripts
      - get: general-task
      - get: daily
        trigger: true
      - task: get-current-container-images
        file: src/container/container-tracking.yml
        image: general-task
        params:
          ATC_URL: https://ci.fr.cloud.gov
          CONCOURSE_AUTH_USERNAME: ((concourse-auth-username))
          CONCOURSE_AUTH_PASSWORD: ((concourse-auth-password))
          CONCOURSE_TEAM_NAME: main

  - name: pages-container-instance-tracking
    plan:
      - get: src
      - get: cg-scripts
      - get: general-task
      - get: daily
        trigger: true
      - task: get-current-container-images
        file: src/container/container-tracking.yml
        image: general-task
        params:
          ATC_URL: https://ci.fr.cloud.gov
          CONCOURSE_AUTH_USERNAME: ((concourse-auth-username))
          CONCOURSE_AUTH_PASSWORD: ((concourse-auth-password))
          CONCOURSE_TEAM_NAME: pages

resources:
  - name: src
    type: git
    source:
      uri: https://github.com/cloud-gov/common-pipelines
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))

  - name: cg-scripts
    type: git
    source:
      uri: https://github.com/cloud-gov/cg-scripts
      branch: main
      commit_verification_keys: ((cloud-gov-pgp-keys))

  - name: daily
    type: time
    source:
      interval: 24h

  - name: general-task
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: general-task
      aws_region: us-gov-west-1
      tag: latest

resource_types:
  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: git
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: git-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: time
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: time-resource
      aws_region: us-gov-west-1
      tag: latest
